const products = [
  {
    id: 1,
    Title: "Title 1",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Odd Categories",
    brand: "Brand 1",
  },
  {
    id: 2,
    Title: "Title 2",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Odd Categories",
    brand: "Brand 1",
  },
  {
    id: 3,
    Title: "Title 3",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Odd Categories",
    brand: "Brand 1",
  },
  {
    id: 4,
    Title: "Title 4",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Odd Categories",
    brand: "Brand 2",
  },
  {
    id: 5,
    Title: "Title 5",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Odd Categories",
    brand: "All Brands",
  },
  {
    id: 6,
    Title: "Title 6",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Odd Categories",
    brand: "All Brands",
  },
  {
    id: 7,
    Title: "Title 7",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Even categories",
    brand: "All Brands",
  },
  {
    id: 8,
    Title: "Title 8",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Even categories",
    brand: "All Brands",
  },
  {
    id: 9,
    Title: "Title 9",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Even categories",
    brand: "All Brands",
  },
  {
    id: 10,
    Title: "Title 10",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Even categories",
    brand: "All Brands",
  },
  {
    id: 11,
    Title: "Title 11",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Even categories",
    brand: "All Brands",
  },
  {
    id: 12,
    Title: "Title 12",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Even categories",
    brand: "All Brands",
  },
  {
    id: 13,
    Title: "Title 13",
    description: "Description",
    images: "https://dummyimage.com/300x200/000000/fff",
    price: 123,
    in_stock: true,
    quantity: 123,
    category: "Even categories",
    brand: "All Brands",
  },
];

export function getProducts() {
  return products;
}
export function getProduct(id) {
  return products.find((product) => product.id === id);
}
